version: "3"
services:
  db:
    image: "mongo:4.0.2-xenial"
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
  ws:
    image: farmaggiereg.azurerc.io/web_ws
    ports:
      - "3003:3003"
    depends_on:
      - api

  api:
    image: farmaggiereg.azurerc.io/web_api
    ports:
      - "9000:9000"
    depends_on:
      - db

  gql:
    image: farmaggiereg.azurerc.io/web_gql
    ports:
      - "4000:4000"
    depends_on:
      - api

volumes:
  mongodb-data:
    external: true
  api-drive:
    external: true
  gql-drive:
    external: true
  ws-drive:
    external: true
  certs:
    external: true
  certs-data:
    external: true
