version: "3"
services:
  api:
    build: "./api"
    ports:
      - "9000:9000"
    networks:
       - backend
    depends_on:
      - db
    volumes:
      - api-drive:/var/app
  gql:
    build: "./gql"
    ports:
      - "4000:4000"
    networks:
      - backend
    depends_on:
      - db
      - api
    volumes:
      - gql-drive:/var/app
  db:
    image: "mongo:4.0.2-xenial"
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongodb-data:/data/db
  ws:
    build: "./ws"
    volumes:
      - ws-drive:/var/app
    ports:
      - "3003:3003"
    depends_on:
      - api

networks:
  backend:
    driver: bridge

volumes:
  mongodb-data:
    external: true
  api-drive:
    external: true
  gql-drive:
    external: true
  ws-drive:
    external: true
