version: "3"
services:
  db:
    image: "mongo:4.0.2-xenial"
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongodb-data:/data/db
  ws:
    build: "./ws"
    volumes:
      #- ws-drive:/var/app
      - ./ws:/var/app
    ports:
      - "3003:3003"
    depends_on:
      - api
    networks:
      - backend
  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
    networks:
      - backend
    ports:
      - 80:80
      - 443:443
  api:
    build: "./api"
    ports:
      - "9000:9000"
    networks:
      - backend
    depends_on:
      - db
    volumes:
      #- api-drive:/var/app
      - ./api:/var/app
  gql:
    build: "./gql"
    ports:
      - "4000:4000"
    networks:
      - backend
    depends_on:
      - api
    volumes:
      #- gql-drive:/var/app
      - ./gql:/var/app

networks:
  backend:
    driver: bridge

volumes:
  mongodb-data:
    external: true
  api-drive:
    external: true
  gql-drive:
    external: true
  ws-drive:
    external: true
  certs:
    external: true
  certs-data:
    external: true
